app_version: v0.5.4
capabilities: []
categories:
- management
date_added: '2025-06-21'
description: "is a free, open-source ..."
home: https://www.tubearchivist.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/<xxx>/icons/icon.svg
keywords:
- tube
- archive
- youtube
lib_version: 2.1.35
lib_version_hash: 1bd4e0058fbd4d7c207df2cae606580065e8e6dba3e232f41bc1b006848b05d2
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: tubearchivist
run_as_context:
- description: TubeArchivist runs as root user.
  gid: 568
  group_name: apps
  uid: 568
  user_name: apps
- description: Redis runs as a non-root user and root group.
  gid: 0
  group_name: root
  uid: 1001
  user_name: redis
screenshots: []
sources:
- https://github.com/tubearchivist/tubearchivist
title: Tube Archivist
train: community
version: 1.0.0
